[nginx-4xx]
enabled = true
port = http,https
filter = nginx-4xx
logpath = /var/log/nginx/detailed-access.log
maxretry = 10
maxmatches = 10
findtime = 600
bantime = 3600
action = nginx-deny-xff[name=nginx-deny-xff]

[nginx-badbots]
enabled = true
port = http,https
filter = nginx-badbots
logpath = /var/log/nginx/detailed-access.log
maxretry = 1
maxmatches = 1
findtime = 600
bantime = 86400
action = nginx-deny-xff[name=nginx-deny-xff]

[nginx-botsearch]
enabled = true
port = http,https
filter = nginx-botsearch
logpath = /var/log/nginx/detailed-access.log
maxretry = 1
findtime = 600
bantime = 86400
action = nginx-deny-xff[name=nginx-deny-xff]

[nginx-ddos]
enabled = true
port = http,https
filter = nginx-ddos
logpath = /var/log/nginx/detailed-access.log
maxretry = 50
findtime = 60
bantime = 86400
action = nginx-deny-xff[name=nginx-deny-xff]

[nginx-limit-req]
enabled = true
port = http,https
filter = nginx-limit-req
logpath = /var/log/nginx/error.log
maxretry = 3
findtime = 300
bantime = 1800
action = nginx-deny-xff[name=nginx-deny-xff]

[nginx-login-bruteforce]
enabled = true
port = http,https
filter = nginx-login-bruteforce
logpath = /var/log/nginx/detailed-access.log
maxretry = 5
findtime = 300
bantime = 3600
action = nginx-deny-xff[name=nginx-deny-xff]

[nginx-noscript]
enabled = true
port = http,https
filter = nginx-noscript
logpath = /var/log/nginx/detailed-access.log
maxretry = 5
findtime = 600
bantime = 3600
action = nginx-deny-xff[name=nginx-deny-xff]

[nginx-modsecurity]
enabled = true
port = http,https
filter = nginx-modsecurity
logpath = /var/log/nginx/error.log
maxretry = 3
findtime = 600
bantime = 3600
action = nginx-deny-xff[name=nginx-deny-xff]