[nginx-limit-req]
enabled = true
port = http,https
filter = nginx-limit-req
logpath = /var/log/nginx/error.log
maxretry = 3
findtime = 300
bantime = 1800

[nginx-login-bruteforce]
enabled = true
port = http,https
filter = nginx-login-bruteforce
logpath = /var/log/nginx/detailed-access.log
maxretry = 5
findtime = 300
bantime = 3600